"""add_subscriptions

Revision ID: 8424dd47a0bd
Revises: 5222e510ad51
Create Date: 2026-03-27 19:22:18.592564
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8424dd47a0bd'
down_revision: Union[str, None] = '5222e510ad51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("plan IN ('monthly', 'yearly')", name='subscriptions_plan_check'),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'expired')", name='subscriptions_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_user')

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
